In [46]:
import pandas as pd

In [48]:
#read data in the raw data from github url

#df = pd.read_csv('https://raw.githubusercontent.com/suneel0101/lesson-plan/master/crunchbase_monthly_export.csv')
#replace na by empty
df = pd.read_csv('https://raw.githubusercontent.com/suneel0101/lesson-plan/master/crunchbase_monthly_export.csv',na_values = [' _ ', "na","*"])

In [ ]:
#find missing value
# df.isnull()
# df.notnull()
df['funding_rounds'].isnull().sum()# do the sum of missing values if exists
df['funding_rounds'].isnull().unique()# check for unique numbers
df['funding_rounds'].isnull().values.any()

In [ ]:
#filling in missing data with the mean
df[' funding_total_usd '] = df[' funding_total_usd '].str.replace(',','')
df[' funding_total_usd '] = df[' funding_total_usd '].str.replace(' ','')

In [ ]:
Convert the data type to float
df[' funding_total_usd '] = df[' funding_total_usd '].astype(float)

In [ ]:
df[' funding_total_usd '] = pd.to_numeric(df[' funding_total_usd '], errors = "coerce" 
df

In [ ]:
df[' funding_total_usd '] = df[' funding_total_usd '].fillna(df[' funding_total_usd '].mean(skipna=True))
df

In [ ]:
df[' funding_total_usd '] = df[' funding_total_usd '].astype(int)
df

In [49]:
df.columns

Index([u'permalink', u'name', u'homepage_url', u'category_list', u' market ',
       u' funding_total_usd ', u'status', u'country_code', u'state_code',
       u'region', u'city', u'funding_rounds', u'founded_at', u'founded_month',
       u'founded_quarter', u'founded_year', u'first_funding_at',
       u'last_funding_at', u'Unnamed: 18'],
      dtype='object')

In [50]:
df.shape

(44950, 19)

In [53]:
#drop 3 columns
df.dropna(subset=['founded_year', 'founded_month','state_code'], inplace = True)
df

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
5,/organization/n-plusn,#NAME?,http://plusn.com,|Software|,Software,"600,000",operating,USA,NY,New York City,New York,1,1/1/12,2012-01,2012-Q1,2012.0,8/29/12,8/29/12,NaN
6,/organization/club-domains,.Club Domains,http://nic.club/,|Software|,Software,"7,000,000",NaN,USA,FL,Ft. Lauderdale,Oakland Park,1,10/10/11,2011-10,2011-Q4,2011.0,5/31/13,5/31/13,NaN
9,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,|Software|,Software,-,operating,USA,IL,"Springfield, Illinois",Champaign,1,1/1/10,2010-01,2010-Q1,2010.0,7/24/14,7/24/14,NaN
10,/organization/0xdata,0xdata,http://www.0xdata.com,|Analytics|,Analytics,"1,700,000",operating,USA,CA,SF Bay Area,Mountain View,1,1/1/11,2011-01,2011-Q1,2011.0,1/3/13,1/3/13,NaN
13,/organization/1-800-dentist,1-800-DENTIST,http://www.1800dentist.com,|Health and Wellness|,Health and Wellness,-,operating,USA,CA,Los Angeles,Los Angeles,1,1/1/86,1986-01,1986-Q1,1986.0,8/19/10,8/19/10,NaN
14,/organization/1-800-doctors,1-800-DOCTORS,http://1800doctors.com,|Health and Wellness|,Health and Wellness,"1,750,000",operating,USA,NJ,Newark,Iselin,1,1/1/84,1984-01,1984-Q1,1984.0,3/2/11,3/2/11,NaN
15,/organization/1-618-technology,1.618 Technology,NaN,|Real Estate|,Real Estate,-,operating,USA,FL,Orlando,Orlando,1,12/7/13,2013-12,2013-Q4,2013.0,1/22/14,1/22/14,NaN
16,/organization/10-20-media,10-20 Media,http://www.10-20media.com,|E-Commerce|,E-Commerce,"2,050,000",operating,USA,MD,Baltimore,Woodbine,4,1/1/01,2001-01,2001-Q1,2001.0,6/18/09,12/28/11,NaN
17,/organization/1000-corks,1000 Corks,http://1000corks.com,|Search|,Search,"40,000",operating,USA,OR,"Portland, Oregon",Lake Oswego,1,1/1/08,2008-01,2008-Q1,2008.0,8/23/11,8/23/11,NaN
20,/organization/1000memories,1000memories,http://1000memories.com,|Curated Web|,Curated Web,"2,535,000",acquired,USA,CA,SF Bay Area,San Francisco,2,7/1/10,2010-07,2010-Q3,2010.0,1/1/10,2/16/11,NaN
21,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,|Curated Web|,Curated Web,"4,462,651",operating,USA,WA,Seattle,Bellevue,4,1/1/08,2008-01,2008-Q1,2008.0,10/14/09,1/15/14,NaN
26,/organization/100plus,100Plus,http://www.100plus.com,|Analytics|,Analytics,"1,250,000",acquired,USA,CA,SF Bay Area,San Francisco,2,9/16/11,2011-09,2011-Q3,2011.0,11/2/11,11/30/11,NaN
27,/organization/1010data,1010data,http://www.1010data.com,|Software|,Software,"35,000,000",operating,USA,NY,New York City,New York,1,1/1/00,2000-01,2000-Q1,2000.0,3/8/10,3/8/10,NaN
28,/organization/10bestthings,10BestThings,http://10bestthings.com,|Curated Web|,Curated Web,"50,000",closed,USA,OH,Cleveland,Cleveland,1,4/1/09,2009-04,2009-Q2,2009.0,4/1/09,4/1/09,NaN
33,/organization/10x-technologies,10X Technologies,http://10xtechnologies.com,|Biotechnology|,Biotechnology,"3,000,000",operating,USA,CA,SF Bay Area,Oakland,1,1/1/12,2012-01,2012-Q1,2012.0,11/7/12,11/7/12,NaN
34,/organization/10x10-room,10X10 Room,http://10x10room.com,|Software|,Software,"77,500",operating,USA,MA,Boston,Lexington,1,1/1/10,2010-01,2010-Q1,2010.0,10/12/11,10/12/11,NaN
40,/organization/121nexus,121nexus,http://www.121nexus.com,|Politics|Technology|Medical Devices|Pharmaceu...,Medical Devices,"794,000",operating,USA,RI,Providence,Providence,6,10/7/11,2011-10,2011-Q4,2011.0,2/6/12,1/1/14,NaN
46,/organization/12society,12Society,http://www.12Society.com,|E-Commerce|,E-Commerce,-,acquired,USA,CA,Los Angeles,West Hollywood,1,1/1/12,2012-01,2012-Q1,2012.0,4/5/12,4/5/12,NaN
47,/organization/1366-technologies,1366 Technologies,http://www.1366tech.com,|Manufacturing|,Manufacturing,"66,450,000",operating,USA,MA,Boston,Bedford,8,1/1/07,2007-01,2007-Q1,2007.0,3/27/08,12/12/13,NaN
50,/organization/140-proof,140 Proof,http://140proof.com,|Twitter Applications|Interest Graph|Advertising|,Advertising,"5,500,000",operating,USA,CA,SF Bay Area,San Francisco,2,1/11/10,2010-01,2010-Q1,2010.0,7/1/09,4/28/11,NaN
51,/organization/140fire,140Fire,http://140fire.com,|Entertainment|Sports|Real Time|Social Media|V...,Advertising,"500,000",operating,USA,CA,Los Angeles,Santa Monica,1,1/1/10,2010-01,2010-Q1,2010.0,5/5/10,5/5/10,NaN
53,/organization/15five,15Five,http://15five.com,|Software|,Software,"1,200,000",operating,USA,CA,SF Bay Area,San Francisco,2,5/1/11,2011-05,2011-Q2,2011.0,1/1/12,1/15/13,NaN
55,/organization/16-mile-solutions,16 Mile Solutions,NaN,|Software|,Software,"199,957",operating,USA,WA,Seattle,Seattle,1,1/1/06,2006-01,2006-Q1,2006.0,6/11/09,6/11/09,NaN
56,/organization/169-st,169 ST.,http://www.junebugreview.com,|Entertainment|Games|,Entertainment,"50,000",closed,USA,FL,Orlando,Lake Mary,1,5/15/09,2009-05,2009-Q2,2009.0,6/1/09,6/1/09,NaN
57,/organization/170-systems,170 Systems,http://www.170systems.com,|Software|,Software,"14,000,000",acquired,USA,MA,Boston,Bedford,1,1/1/90,1990-01,1990-Q1,1990.0,4/16/02,4/16/02,NaN
64,/organization/1cast,1Cast,http://www.1cast.com,|Lifestyle|Content|Video|News|,Content,-,closed,USA,WA,Seattle,Kirkland,1,6/1/06,2006-06,2006-Q2,2006.0,8/12/08,8/12/08,NaN
69,/organization/1daymakeover,1DayMakeover,http://www.1daymakeover.com,|Shopping|Cosmetics|Personal Health|Lifestyle|...,Cosmetics,"50,000",closed,USA,CA,"Orange County, California",Santa Ana,1,6/30/08,2008-06,2008-Q2,2008.0,6/30/08,6/30/08,NaN
70,/organization/1docway,1DocWay,http://1docway.com,|None|,None,-,operating,USA,PA,Philadelphia,Philadelphia,1,2/1/11,2011-02,2011-Q1,2011.0,8/10/11,8/10/11,NaN
71,/organization/1energy-systems,1Energy Systems,http://1energysystems.com,|Software|,Software,"1,450,000",operating,USA,WA,Seattle,Seattle,1,1/1/10,2010-01,2010-Q1,2010.0,4/22/13,4/22/13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44888,/organization/zuli,Zuli,http://zuli.io,|Mobile Software Tools|Mobile|,Mobile,-,operating,USA,CA,SF Bay Area,San Francisco,2,1/1/12,2012-01,2012-Q1,2012.0,7/19/12,9/20/13,NaN
44889,/organization/zulily,zulily,http://www.zulily.com,|Babies|Flash Sales|E-Commerce|,Babies,"138,600,000",operating,USA,WA,Seattle,Seattle,4,1/1/10,2010-01,2010-Q1,2010.0,12/17/09,11/15/12,NaN
44890,/organization/zulu,Zulu,http://www.zulu-inc.com,|Software|,Software,"1,070,000",operating,USA,CA,SF Bay Area,San Jose,2,2/28/12,2012-02,2012-Q1,2012.0,8/1/12,3/26/13,NaN
44891,/organization/zumatek,zumatek,http://zumatek.com,|Biotechnology|,Biotechnology,"150,000",operating,USA,NC,Raleigh,Chapel Hill,1,1/1/05,2005-01,2005-Q1,2005.0,11/23/10,11/23/10,NaN
44892,/organization/zumba-fitness,Zumba Fitness,http://www.zumba.com,|Health and Wellness|,Health and Wellness,-,operating,USA,FL,Florida,Hallandale,1,1/1/01,2001-01,2001-Q1,2001.0,3/8/12,3/8/12,NaN
44894,/organization/zumbox,Zumbox,http://blogs.wsj.com/venturecapital/2014/04/10...,|Curated Web|,Curated Web,"28,300,000",closed,USA,CA,Los Angeles,Los Angeles,4,10/1/06,2006-10,2006-Q4,2006.0,6/23/08,7/10/12,NaN
44895,/organization/zume-life,Zume Life,http://www.zumelife.com,|iPhone|Social Network Media|Health and Wellne...,Health and Wellness,"1,700,000",closed,USA,CA,SF Bay Area,San Jose,2,7/25/06,2006-07,2006-Q3,2006.0,1/1/07,4/1/08,NaN
44896,/organization/zumeo-com,Zumeo.com,http://www.zumeodesign.com/,|Recruiting|Internet|Social Network Media|Empl...,Employment,"100,000",operating,USA,OR,Medford,Medford,1,5/1/07,2007-05,2007-Q2,2007.0,1/29/09,1/29/09,NaN
44897,/organization/zumi-networks,Zumi Networks,http://www.zuminetworks.com,|Mobile|Promotional|Analytics|Ediscovery|Apps|...,Advertising,"500,000",operating,USA,WA,Seattle,Kirkland,1,9/1/13,2013-09,2013-Q3,2013.0,10/1/13,10/1/13,NaN
44898,/organization/zumigo,Zumigo,http://www.zumigo.com,|Mobile|,Mobile,"5,120,000",operating,USA,CA,SF Bay Area,San Jose,3,1/1/08,2008-01,2008-Q1,2008.0,12/28/10,10/13/13,NaN
44900,/organization/zumobi,Zumobi,http://www.zumobi.com,|Mobile|,Mobile,"12,000,000",operating,USA,WA,Seattle,Seattle,1,3/1/07,2007-03,2007-Q1,2007.0,5/7/07,5/7/07,NaN
44902,/organization/zuora,Zuora,http://www.zuora.com,|Facebook Applications|Payments|Billing|SaaS|S...,Billing,"127,500,000",operating,USA,CA,SF Bay Area,Foster City,5,1/1/07,2007-01,2007-Q1,2007.0,3/13/08,9/5/13,NaN
44905,/organization/zurex-pharma,Zurex Pharma,http://www.zurex-pharma.com,|Health Care|,Health Care,"11,146,457",operating,USA,WI,Wisconsin,Middleton,4,1/1/10,2010-01,2010-Q1,2010.0,5/2/11,7/2/14,NaN
44912,/organization/zuujit,Zuujit,http://www.zuujit.com,|E-Commerce|,E-Commerce,"2,700,000",closed,USA,CA,Santa Barbara,Santa Barbara,1,1/1/10,2010-01,2010-Q1,2010.0,4/30/10,4/30/10,NaN
44913,/organization/zuuka,zuuka!,http://www.istorytime.com,|Apps|Publishing|Entertainment|Kids|Mobile|,Apps,-,acquired,USA,CA,Santa Barbara,Santa Barbara,2,4/10/09,2009-04,2009-Q2,2009.0,1/24/11,6/11/12,NaN
44917,/organization/zvents,Zvents,http://www.zvents.com,|Nightlife|Music|Kids|Ticketing|Concerts|Enter...,Concerts,"31,200,000",acquired,USA,CA,SF Bay Area,San Mateo,3,3/1/05,2005-03,2005-Q1,2005.0,10/5/05,9/30/08,NaN
44918,/organization/zwamy,Zwamy,NaN,|None|,None,"387,794",operating,USA,CA,SF Bay Area,Los Altos Hills,1,1/1/13,2013-01,2013-Q1,2013.0,4/2/14,4/2/14,NaN
44919,/organization/zweemie,Zweemie,http://www.tellasksell.com,|Messaging|,Messaging,"250,000",operating,USA,MI,Flint,Grand Blanc,1,1/1/09,2009-01,2009-Q1,2009.0,6/3/10,6/3/10,NaN
44922,/organization/zwittle,Zwittle,http://zwittle.com,|Software|,Software,"190,000",operating,USA,UT,Salt Lake City,Logan,1,1/1/11,2011-01,2011-Q1,2011.0,4/19/12,4/19/12,NaN
44924,/organization/zyante,Zyante,http://www.zyante.com,|News|,News,"870,000",operating,USA,CA,SF Bay Area,Los Gatos,2,1/1/12,2012-01,2012-Q1,2012.0,12/1/13,4/2/14,NaN
44926,/organization/zyga-technology,Zyga,http://www.zyga.com,|Medical Devices|Health Care|,Health Care,"45,750,000",operating,USA,MN,Minneapolis,Minnetonka,4,1/1/08,2008-01,2008-Q1,2008.0,10/6/08,12/16/13,NaN
44930,/organization/zykis,Zykis,http://zykis.com,|Data Security|Automotive|Portals|Education|Ki...,Automotive,"800,000",closed,USA,CA,Anaheim,Irvine,1,10/27/06,2006-10,2006-Q4,2006.0,10/27/06,10/27/06,NaN
44931,/organization/zylie-the-bear,Zylie the Bear,http://zyliethebear.com,|E-Commerce|,E-Commerce,"75,000",operating,USA,CT,Hartford,Greenwich,1,1/1/09,2009-01,2009-Q1,2009.0,6/7/12,6/7/12,NaN
44932,/organization/zyme-solutions,Zyme Solutions,http://www.zymesolutions.com,|Hardware|Hardware + Software|,Hardware,"12,039,999",operating,USA,CA,California,Redwood Shores,5,1/1/04,2004-01,2004-Q1,2004.0,9/12/05,5/1/14,NaN
44933,/organization/zymetis,Zymetis,http://www.zymetis.com,|Biotechnology|,Biotechnology,"2,257,464",closed,USA,MD,Maryland,College Park,2,1/1/06,2006-01,2006-Q1,2006.0,1/11/10,1/31/10,NaN
44934,/organization/zymeworks,Zymeworks,http://zymeworks.com,|Biotechnology|,Biotechnology,"38,900,000",operating,CAN,AB,Vancouver,Vancouver,5,4/1/04,2004-04,2004-Q2,2004.0,3/3/08,1/9/14,NaN
44938,/organization/zynga,Zynga,http://www.zynga.com,|Technology|Facebook Applications|Networking|G...,Facebook Applications,"866,550,786",operating,USA,CA,SF Bay Area,San Francisco,9,7/1/07,2007-07,2007-Q3,2007.0,1/1/07,2/18/11,NaN
44939,/organization/zyngenia,Zyngenia,http://www.zyngenia.com,|Biotechnology|,Biotechnology,"25,000,000",operating,USA,MD,Maryland,Gaithersburg,1,1/1/08,2008-01,2008-Q1,2008.0,9/9/10,9/9/10,NaN
44941,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,|Biotechnology|,Biotechnology,"34,275,015",operating,USA,MO,Missouri,Fremont,4,1/1/98,1998-01,1998-Q1,1998.0,1/29/10,3/26/14,NaN
44949,/organization/x,[x+1],http://www.xplusone.com/,|Enterprise Software|,Enterprise Software,"45,000,000",operating,USA,NY,New York City,New York,4,1/1/99,1999-01,1999-Q1,1999.0,6/1/08,4/4/13,NaN

In [ ]:
# want to get 90% of the column value
df[' funding_total_usd '] = df[' funding_total_usd ']

In [42]:
# df1=df.loc[-1]
# df1 = df.drop('')
#df.drop(df.columns[[0, 1, 3]], axis=1)
#df2= df.drop(df.columns[[18]], axis =1)
#df1 = df.drop('Unnamed: 18',)
df.dropna(axis =1, "Unnamed: 18" ,how = 'all', inplace =True)

SyntaxError: non-keyword arg after keyword arg (<ipython-input-42-6a92cd4834fc>, line 6)

In [40]:
df[0:10]

TypeError: 'NoneType' object has no attribute '__getitem__'

In [13]:
df.columns
#df.head()

Index([u'permalink', u'name', u'homepage_url', u'category_list', u' market ',
       u' funding_total_usd ', u'status', u'country_code', u'state_code',
       u'region', u'city', u'funding_rounds', u'founded_at', u'founded_month',
       u'founded_quarter', u'founded_year', u'first_funding_at',
       u'last_funding_at', u'Unnamed: 18'],
      dtype='object')

In [24]:
dummy_1= pd.get_dummies(df[' market '])
dummy_1

,3D,3D Printing,3D Technology,Accounting,Active Lifestyle,Ad Targeting,Advanced Materials,Adventure Travel,Advertising,Advertising Exchanges,...,Web Hosting,Web Tools,Weddings,Wholesale,Wine And Spirits,Wireless,iOS,iPad,iPhone,mHealth
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44920,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44921,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44922,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44923,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44924,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44925,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44926,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44928,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44929,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44930,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44931,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44932,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44933,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44934,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44935,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44936,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44937,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44946,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44947,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44948,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44949,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df[' funding_total_usd ']=df[' funding_total_usd '].astype(float)

ValueError: invalid literal for float(): 45,000,000

In [33]:
#df[' funding_total_usd '] =pd.to_numeric(df[' funding_total_usd '], errors ='coerce')
df[' funding_total_usd '] =df[' funding_total_usd '].str.replace(',' '')
df[' funding_total_usd ']

AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas

In [28]:
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,NaN,NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,NaN,acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,NaN,operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,NaN,operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,NaN,operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN

In [34]:
df.dtypes

permalink               object
name                    object
homepage_url            object
category_list           object
 market                 object
 funding_total_usd     float64
status                  object
country_code            object
state_code              object
region                  object
city                    object
funding_rounds           int64
founded_at              object
founded_month           object
founded_quarter         object
founded_year           float64
first_funding_at        object
last_funding_at         object
Unnamed: 18            float64
dtype: object

In [41]:
%%HTML
<script type='text/javascript' src='https://10az.online.tableau.com/javascripts/api/viz_v1.js'></script><div class='tableauPlaceholder' style='width: 1268px; height: 665px;'><object class='tableauViz' width='1268' height='665' style='display:none;'><param name='host_url' value='https%3A%2F%2F10az.online.tableau.com%2F' /> <param name='site_root' value='&#47;t&#47;maxime' /><param name='name' value='Project_test&#47;Sheet2' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='showShareOptions' value='true' /></object></div>